name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Yarn Berry
        run: |
          corepack enable
          yarn set version berry

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn eslint .

      - name: Run Tests
        run: yarn test
